"""
After running the calibrations on the VMs, run this script on the VMs to generate the files
used for creating figures 1 and 2 in the paper.
All the files generated by this script can be added to the repository.
"""


# %% Imports and settings
import sciris as sc
import pandas as pd
import utils as ut
from run_sims import run_msim, save_stats


if __name__ == '__main__':

    # Settings
    sc.heading('Saving plot files')

    sims = run_msim(scenan_pars=50, use_calib=True, seed=1, debug=False, do_save=False)
    save_stats(sims)

    print('Done!')


