"""
Run calibrations for the STI model
"""

# Additions to handle numpy multithreading
import os
os.environ.update(
    OMP_NUM_THREADS='1',
    OPENBLAS_NUM_THREADS='1',
    NUMEXPR_NUM_THREADS='1',
    MKL_NUM_THREADS='1',
)

# %% Imports and settings
import numpy as np
import sciris as sc
import stisim as sti
import pandas as pd
from run_sims import make_sim


# Constants
LOCATION = 'zimbabwe'
DATA_DIR = 'data'
RESULTS_DIR = 'results'
FIGURES_DIR = 'figures'


# Run settings
TOTAL_TRIALS = 2000
storage = None
do_shrink = True  # Whether to shrink the calibration results


def make_calibration():

    # Define the calibration parameters
    ckw = dict(suggest_type='suggest_float')
    calib_pars = dict(
        hiv=dict(
            beta_m2f=      dict(low=0.002, high=0.014, guess=0.006, **ckw),
            eff_condom=    dict(low=0.5, high=0.9, guess=0.75, **ckw),
            rel_init_prev= dict(low=2, high=15, guess=8, **ckw),
            rel_dur_on_art=dict(low=1.0, high=20.0, guess=8.0, **ckw),
        ),
        structuredsexual=dict(
            prop_f0= dict(low=0.55, high=0.9, guess=0.7, **ckw),
            prop_m0= dict(low=0.55, high=0.8, guess=0.65, **ckw),
            m1_conc= dict(low=0.05, high=0.3, guess=0.15, **ckw),
        ),
        syph=dict(
            beta_m2f=          dict(low=0.15, high=0.35, guess=0.2, **ckw),
            eff_condom=        dict(low=0.3, high=0.7, guess=0.5, **ckw),
            rel_trans_primary= dict(low=3, high=10, guess=6, **ckw),
        ),
        **{  # hiv_syph has an underscore so can't use keyword syntax
            'hiv_syph': dict(
                rel_sus_syph_hiv= dict(low=1.0, high=3.0, guess=1.5, **ckw),
                rel_sus_hiv_syph= dict(low=1.5, high=4.0, guess=2.67, **ckw),
            ),
        },
        symp_algo=  dict(rel_test=dict(low=0.5, high=1.5, guess=1.0, **ckw)),
        anc_screen= dict(rel_test=dict(low=0.7, high=1.8, guess=1.0, **ckw)),
        dual_hiv=   dict(rel_test=dict(low=0.5, high=1.7, guess=1.0, **ckw)),
    )

    # Minimal extra results — just core epi for calibration display.
    # Comprehensive results are generated by run_msim.py with the best pars.
    sres = ['hiv.n_on_art', 'n_alive', 'syph.n_active', 'syph.active_prevalence',
            'syph.new_congenital', 'hiv.new_deaths']

    sim = make_sim(verbose=-1, seed=1)
    data = pd.read_csv(f'data/{LOCATION}_all_data.csv')

    weights = {
        # HIV — upweighted to prevent bimodal calibration (bad HIV + good syphilis)
        'hiv.prevalence_15_49': 5.0,
        'hiv.n_infected': 2.0,
        'hiv.new_infections': 2.0,
        'hiv.n_on_art': 2.0,
        # Syphilis
        'syph.n_active': 10.0,
        'syph.new_infections': 10.0,
        'syph.active_prevalence': 10.0,
        'syph.active_prevalence_f': 20.0,                       # ZIMPHIA survey — high weight
        'syph.active_prevalence_m': 20.0,                       # ZIMPHIA survey — high weight
        'active_coinfection_stats.syph_prev_has_hiv': 20.0,     # ZIMPHIA — active syph in HIV+
        'active_coinfection_stats.syph_prev_no_hiv': 20.0,      # ZIMPHIA — active syph in HIV-
    }

    # Pre-sim prune: reject parameter combos likely to cause syphilis die-out
    def prune_low_syph_transmission(pars):
        beta = pars.get('syph.beta_m2f', {}).get('value', 0.15)
        rtp = pars.get('syph.rel_trans_primary', {}).get('value', 5)
        eff = pars.get('syph.eff_condom', {}).get('value', 0.5)
        force = beta * rtp * (1 - eff)
        return force < 0.5  # Prune if effective force is too low

    # Post-sim check: reject trials where syphilis died out or HIV prevalence is too low
    def check_sim_alive(sim):
        if sim is None:
            return False
        syph_ni = sim.results.syph.new_infections[-60:]
        if np.sum(syph_ni) == 0:
            return False
        hiv_prev = sim.results.hiv.prevalence_15_49[-60:]
        if np.median(hiv_prev) < 0.05:
            return False
        return True

    calib = sti.Calibration(
        calib_pars=calib_pars,
        extra_results=sres,
        weights=weights,
        sim=sim,
        data=data,
        prune_fn=prune_low_syph_transmission,
        check_fn=check_sim_alive,
        study_name=f'{LOCATION}_calibration_v21',
        total_trials=TOTAL_TRIALS,
        die=False, reseed=False, storage=storage, save_results=True,
        continue_db=True, keep_db=True,
    )

    return sim, calib


if __name__ == '__main__':

    do_run = True

    if do_run:
        sim, calib = make_calibration()
        sc.heading(f'Running calibration, {TOTAL_TRIALS} trials')
        calib.calibrate()
        print(f'Best pars are {calib.best_pars}')
        calib.remove_db()
        calib.save(f'{RESULTS_DIR}/{LOCATION}_calib_all.obj', shrink=do_shrink,
                   pars_filename=f'{RESULTS_DIR}/{LOCATION}_pars_all.df')
    else:
        calib = sc.loadobj(f'{RESULTS_DIR}/{LOCATION}_calib_all.obj')

    print('Done!')


